### PR TITLE
Update VMC multiple engines section

### PR DESCRIPTION
**Pull request by benedikt-voelkel**

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
Hello @ihrivnac 
I hope this addresses all your comments discussed via email

**Comment by ihrivnac** [comment]
Hi @benedikt-voelkel ,
Thank you for the update. The cpp blocks declared via ``` do not display well with hugo.  Could you, please, change them with the following syntax:
```
{{< highlight cpp >}}
...
{{< /highlight >}}

```
There is also repeated the item numbering (1) in the ordered list.

You can check the generated documentation by running 
`hugo server -D`
in the top vmc-documentation directory and then open the generated link (which will be printed on the screen) in a web browser.

**Comment by benedikt-voelkel** [comment]
Hej @ihrivnac 
I fixed the highlighting of the C++ code. And I had a look yesterday as well already with hugo locally. It's funny, I didn't see the numbering problem. However, in the source there was a (2) repeated for the very last list.
Usually, in markdown, it doesn't matter which numbering one chooses and it just increments when it finds an ordered list. Maybe we have different hugo versions? Mine is `v0.58.3`

**Comment by ihrivnac** [comment]
Hi @benedikt-voelkel ,

Thanks for the changes; I was not clear enough for the numbering lists; the item numbering (1) appeared in the browser, probably due to the empty line(s) between the items; so I did not asked for change the numbers in the source, but for fixing the item which appear with a successive number. Now, when I change back 1,2,3,4 to 1,1,1,1 in both lists, they look ok in the browser. As this style is preferred, could you, please, put 1's back here.

The cpp code appears ok now.

My hugo version is v0.55.6, so the differences which we observe may be caused by different versions. I will try to update mine when I get to it.

**Comment by benedikt-voelkel** [comment]
Hej @ihrivnac ,
I updated all lists to have item "1" in the source. I hope that fixes what you see on your side.

**Pull request merged**
